# ------------------------------------------------------------------------------
# Script:       00_RUN_Province_Damage_Update.R
# Purpose:      Orchestrates the entire forest damage detection and mapping pipeline for the province.
#               It manages data flow, backups, and calls subsequent R scripts to
#               process satellite imagery, detect damage, and generate final products.
# Date:         26_05_2025
#
# Inputs:
#   - Previous run files (from /mnt/CEPH_PROJECTS/WALDSCHAEDEN/working_folder/outputs/fordead_15)
#   - Final yearly and monthly damage products (generated by 06_Integrate_And_Refine_Damage_Products.R)
#   - Hardcoded paths to historical yearly/monthly shapefiles for area comparison
#
# Outputs:
#   - Backed-up previous run files in a timestamped directory.
#   - Final yearly and monthly damage GeoTIFFs and Shapefiles (prepared for upload).
#
# Operations:
#   1. Sets the working directory.
#   2. Defines global parameters like `update_name` and `outfold`.
#   3. Manages backup of previous run files to ensure data integrity.
#   4. Sequentially sources the following R scripts to execute the pipeline steps:
#      - 01_Import_S2_data.R: Manages satellite imagery acquisition and organization.
#      - 03_Mosaic_FORDEAD_Outputs.R: Merges tiled FORDEAD outputs.
#      - 04_Refine_And_Mask_Damage_Products.R: Refines and masks damage products.
#      - 05_Style_And_Project_Damage_Maps.R: Prepares and styles damage maps for output.
#      - 06_Integrate_And_Refine_Damage_Products.R: Integrates historical data and applies final filters.
#   5. Generates raster overviews (pyramids) for the final GeoTIFF products using `gdaladdo`.
#   6. Prepares `scp` commands for uploading the final yearly and monthly damage products.
#   7. Performs area comparisons with historical damage data using `terra` functions.
# ------------------------------------------------------------------------------

setwd("/mnt/CEPH_PROJECTS/WALDSCHAEDEN/Scripts_fordead_forest_service/")

update_name = "july" # name of the update, usually just the month
outfold <- "/mnt/CEPH_PROJECTS/WALDSCHAEDEN/Products/FORDEAD_01_07_2025/" # last image

# Before starting, manually make a copy of the folder "fordead_15", just in case something went wrong with the update (~55 mins)
# since the updates always build on the latest one, always keep at least one copy
# the copy is in fordead_15_updates/fordead_15

# Save the output of the previous run to backup folder (outputs of post processing only)
prev_run_files = list.files("/mnt/CEPH_PROJECTS/WALDSCHAEDEN/working_folder/outputs/fordead_15", full.names = T)
prev_run_files = prev_run_files[!file.info(prev_run_files)$isdir]

# if files from previous run are found, move them to a backup dir
if(length(prev_run_files) > 0) {
  new_dir <- "/mnt/CEPH_PROJECTS/WALDSCHAEDEN/working_folder/outputs/fordead_15_forest_service_updates/jun_2025/" # target directory
  # Create new paths by replacing the directory
  dir.create(new_dir)
  new_paths <- file.path(new_dir, basename(prev_run_files))
  # Move files
  file.rename(from = prev_run_files, to = new_paths)
}

# Script calls
source("B_RUN_simple.R")
source("2B_merge_tiled_outputs.R")
source("3B_index_merging.R")
source("4-5B_revised.R")
source("06_Integrate_And_Refine_Damage_Products.R")

# Finalize

# --- Generate Overviews (Pyramids) --- file names are defined in the last script
system(paste0('gdaladdo -r mode ', raster_filename_month, ' 2 4 8 16 32'))
system(paste0('gdaladdo -r mode ', raster_filename_year, ' 2 4 8 16 32'))

# upload - run in terminal

paste0("scp ", raster_filename_year," eo_forest@193.106.181.22:changes_yearly_damages_latest.tif")
#password: AqyowLyoNkqRGMTmJK8Z
paste0("scp ", raster_filename_month," eo_forest@193.106.181.22:changes_monthly_damages_latest.tif")








# Compare areas 
library(terra)

# --- Load Vector Data ---
# previous_run <- vect("/mnt/CEPH_PROJECTS/WALDSCHAEDEN/Products/FORDEAD_25_08_2024/changes_yearly_damages_aug_2024_25832.shp")
previous_run <- vect("/mnt/CEPH_PROJECTS/WALDSCHAEDEN/Products/FORDEAD_03_11_2024/changes_yearly_damages_oct_2024_25832.shp")
sept_run     <- vect("/mnt/CEPH_PROJECTS/WALDSCHAEDEN/Products/FORDEAD_30_09_2024/changes_yearly_damages_sept_2024_25832.shp")
current_run  <- vect("/mnt/CEPH_PROJECTS/WALDSCHAEDEN/Products/FORDEAD_09_06_2025/changes_yearly_damages_june_2025_25832_final.shp")

# --- Area Calculations ---
expanse(current_run, unit = "ha")
expanse(sept_run, unit = "ha")
expanse(previous_run, unit = "ha")

