# ------------------------------------------------------------------------------
# Script:       03_Mosaic_FORDEAD_Outputs.R
# Purpose:      Mosaics the tiled outputs generated by the FORDEAD process for each
#               vegetation index into full-area maps (both raster and vector).
# Date:         (Original Date from script, if available)
#
# Inputs:
#   - Tiled FORDEAD outputs (e.g., `confidence_index.tif`, `dieback.shp`, `stress_periods.shp`,
#     `mask_nodata.tif`, `valid_obs.tif`, `first_date_dieback.tif`, etc.) from `for_out_path`.
#   - `index.list` (implicitly from `02_Execute_Core_FORDEAD_Processing.R`).
#
# Outputs:
#   - Merged GeoTIFFs and Shapefiles for various outputs (e.g., `output_NDWI_merged.shp`,
#     `output_confidence_NDVI_merged.tif`) in `for_out_path`.
#
# Operations:
#   1. Loops through each vegetation index specified in `index.list`.
#   2. Identifies and merges corresponding tiled vector files (e.g., dieback, stress, soil) using `terra::vect` and `rbind`.
#   3. Identifies and merges corresponding tiled raster files (e.g., confidence indices, nodata masks, valid observations,
#      first date of dieback, stress-related metrics, soil status) using `terra::vrt` and `writeRaster`.
# ------------------------------------------------------------------------------
#### Mosaic outputs #####

# This script mosaics the tiled outputs into full area maps, which are the input 
# for the steps that follow

# Some layers are mosaiced only for visualization purposes (not necesary for the following steps, )

#index.list = c("NDVI", "NDWI")

for (i in index.list) {
  # Iterate through each vegetation index (e.g., NDVI, NDWI) to mosaic its corresponding tiled outputs.
  gc()
  
  # List output directories for the current vegetation index.
  dirs.out = list.dirs(for_out_path, full.names = T, recursive = F)
  dirs.out = dirs.out[grep(paste0("^fordead_output_", i), basename(dirs.out))]
  
  
  # List output directories for the current vegetation index.
  dirs.out = list.dirs(for_out_path, full.names = T, recursive = F)
  dirs.out = dirs.out[grep(paste0("^fordead_output_", i), basename(dirs.out))]
  # FLAG: Fragile logic. Filtering directories based on a hardcoded character length (98) is not robust.
  # This will break if the path length changes.
  dirs.out = dirs.out[nchar(dirs.out) == 98] # Filter directories based on character length to select specific output folders. This value (98) may need adjustment if the `for_out_path` name changes or if running in a subfolder.
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "confidence_index.tif", full.names = T)
  
  # dieback
  
  # List all tiled dieback shapefiles within the identified output directories.
  per.res.die = list.files(dirs.out, recursive = T, pattern = "dieback.shp", full.names = T)
  
  output = vect(per.res.die[1])
  for (res in per.res.die[2:length(per.res.die)]) {
    a = vect(res)
    output = rbind(a, output)
  }
  writeVector(output, paste0(for_out_path, paste0("output_", i, "_merged.shp")))
  # Write the merged dieback shapefile to the output directory.
  
  # stress
  
  # List all tiled stress period shapefiles within the identified output directories.
  per.res.die = list.files(dirs.out, recursive = T, pattern = "stress_periods.shp$", full.names = T)
  
  output = vect(per.res.die[1])
  for (res in per.res.die[2:length(per.res.die)]) {
    a = vect(res)
    output = rbind(a, output)
  }
  writeVector(output, paste0(for_out_path, paste0("output_stress_", i, "_merged.shp")))
  # Write the merged stress period shapefile to the output directory.
  
  gc()
  
  # soil
  
  # List all tiled soil shapefiles within the identified output directories.
  per.res.die = list.files(dirs.out, recursive = T, pattern = "periodic_results_soil.shp$", full.names = T)
  
  output = vect(per.res.die[1])
  for (res in per.res.die[2:length(per.res.die)]) {
    a = vect(res)
    output = rbind(a, output)
  }
  writeVector(output, paste0(for_out_path, paste0("output_soil_", i, "_merged.shp")))
  # Write the merged soil shapefile to the output directory.
  
  # merge confidence indices
  # List all tiled confidence index raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "confidence_index.tif", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled confidence index files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_confidence_", i, "_merged.tif")))
  # Write the merged confidence index raster to a TIFF file.
  
  
  # merge nodata masks
  # List all tiled nodata mask raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "mask_nodata.tif", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled nodata mask files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_nodata_", i, "_merged.tif")))
  
  gc()
  
  # merge n obs
  # List all tiled valid observation raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "valid_obs.tif", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled valid observation files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_valid_obs_", i, "_merged.tif")))
  # Write the merged valid observation raster to a TIFF file.
  
  
  # merge start date dieback
  # List all tiled first date of dieback raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "first_date_dieback.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled first date of dieback files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_dirst_date_dieback_", i, "_merged.tif")))
  
  
  # merge start date unconfirmed dieback
  # List all tiled first date of unconfirmed dieback raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "first_date_unconfirmed_dieback.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled unconfirmed dieback files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_dirst_date_unconfirmed_dieback_", i, "_merged.tif")))
  
  gc()
  
  # merge start date unconfirmed dieback
  # List all tiled count dieback raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "count_dieback.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled count dieback files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_count_dieback_", i, "_merged.tif")))
  
  # merge start date cum diff stress
  # List all tiled cumulative difference stress raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "cum_diff_stress.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled cumulative difference stress files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_cum_diff_stress_", i, "_merged.tif")))
  
  # merge start date dates stress
  # List all tiled dates stress raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "dates_stress.tif$", full.names = T)
  conf.res.die = conf.res.die[!grepl("nb_dates", conf.res.die)]
  # Filter out files that contain "nb_dates" in their names to avoid processing them as stress dates.
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled dates stress files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_dates_stress_", i, "_merged.tif")))
  
  stress_durations = conf_merged[[2]] - conf_merged[[1]] # Calculate stress durations as the difference between the first anomaly and first normal observation.
  
  for (m in 2:((nlyr(conf_merged)-1)/2)) stress_durations = c(stress_durations, conf_merged[[2*m]] - conf_merged[[2*m-1]])
  # Calculate stress durations for multiple periods.
  
  writeRaster(stress_durations, paste0(for_out_path, paste0("output_dates_stress_diff_", i, "_merged.tif")))
  # Write the calculated stress durations to a TIFF file.
  
  gc()
  
  # merge nb date dates stress
  # List all tiled number of dates stress raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "nb_dates_stress.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled number of dates stress files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_nb_dates_stress_", i, "_merged.tif")))
  
  # merge nb periods stress
  # List all tiled number of periods stress raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "nb_periods_stress.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled number of periods stress files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_nb_periods_stress_", i, "_merged.tif")))
  
  # merge stress index
  # List all tiled stress index raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "stress_index.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled stress index files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_stress_index_", i, "_merged.tif")))
  
  gc()
  
  # merge soil status
  # List all tiled soil status raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "state_soil.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled soil status files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("state_soil_", i, "_merged.tif")))
  
  # merge soil count
  # List all tiled soil count raster files within the identified output directories.
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "count_soil.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  # Create a virtual raster (VRT) from the list of tiled soil count files.
  writeRaster(conf_merged, paste0(for_out_path, paste0("count_soil_", i, "_merged.tif")))
  
  gc()
}
