# ------------------------------------------------------------------------------
# Script:       03_Mosaic_FORDEAD_Outputs.R
# Purpose:      Mosaics the tiled outputs generated by the FORDEAD process for each
#               vegetation index into full-area maps (both raster and vector).
# Date:         (Original Date from script, if available)
#
# Inputs:
#   - Tiled FORDEAD outputs (e.g., `confidence_index.tif`, `dieback.shp`, `stress_periods.shp`,
#     `mask_nodata.tif`, `valid_obs.tif`, `first_date_dieback.tif`, etc.) from `for_out_path`.
#   - `index.list` (implicitly from `02_Execute_Core_FORDEAD_Processing.R`).
#
# Outputs:
#   - Merged GeoTIFFs and Shapefiles for various outputs (e.g., `output_NDWI_merged.shp`,
#     `output_confidence_NDVI_merged.tif`) in `for_out_path`.
#
# Operations:
#   1. Loops through each vegetation index specified in `index.list`.
#   2. Identifies and merges corresponding tiled vector files (e.g., dieback, stress, soil) using `terra::vect` and `rbind`.
#   3. Identifies and merges corresponding tiled raster files (e.g., confidence indices, nodata masks, valid observations,
#      first date of dieback, stress-related metrics, soil status) using `terra::vrt` and `writeRaster`.
# ------------------------------------------------------------------------------
#### Mosaic outputs #####

# This script mosaics the tiled outputs into full area maps, which are the input 
# for the steps that follow

# Some layers are mosaiced only for visualization purposes (not necesary for the following steps, )

#index.list = c("NDVI", "NDWI")

for (i in index.list) {
  
  gc()
  
  dirs.out = list.dirs(for_out_path, full.names = T, recursive = F)
  dirs.out = dirs.out[grep(paste0("^fordead_output_", i), basename(dirs.out))]
  
  
  dirs.out = list.dirs(for_out_path, full.names = T, recursive = F)
  dirs.out = dirs.out[grep(paste0("^fordead_output_", i), basename(dirs.out))]
  dirs.out = dirs.out[nchar(dirs.out) == 98] # revert to 98 / adjust if running in a subfolder or if for_out_path name has changed
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "confidence_index.tif", full.names = T)
  
  # dieback
  
  per.res.die = list.files(dirs.out, recursive = T, pattern = "dieback.shp", full.names = T)
  
  output = vect(per.res.die[1])
  for (res in per.res.die[2:length(per.res.die)]) {
    a = vect(res)
    output = rbind(a, output)
  }
  writeVector(output, paste0(for_out_path, paste0("output_", i, "_merged.shp")))
  
  # stress
  
  per.res.die = list.files(dirs.out, recursive = T, pattern = "stress_periods.shp$", full.names = T)
  
  output = vect(per.res.die[1])
  for (res in per.res.die[2:length(per.res.die)]) {
    a = vect(res)
    output = rbind(a, output)
  }
  writeVector(output, paste0(for_out_path, paste0("output_stress_", i, "_merged.shp")))
  
  gc()
  
  # soil
  
  per.res.die = list.files(dirs.out, recursive = T, pattern = "periodic_results_soil.shp$", full.names = T)
  
  output = vect(per.res.die[1])
  for (res in per.res.die[2:length(per.res.die)]) {
    a = vect(res)
    output = rbind(a, output)
  }
  writeVector(output, paste0(for_out_path, paste0("output_soil_", i, "_merged.shp")))
  
  # merge confidence indices
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "confidence_index.tif", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_confidence_", i, "_merged.tif")))
  
  
  # merge nodata masks
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "mask_nodata.tif", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_nodata_", i, "_merged.tif")))
  
  gc()
  
  # merge n obs
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "valid_obs.tif", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_valid_obs_", i, "_merged.tif")))
  
  
  # merge start date dieback
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "first_date_dieback.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_dirst_date_dieback_", i, "_merged.tif")))
  
  
  # merge start date unconfirmed dieback
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "first_date_unconfirmed_dieback.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_dirst_date_unconfirmed_dieback_", i, "_merged.tif")))
  
  gc()
  
  # merge start date unconfirmed dieback
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "count_dieback.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_count_dieback_", i, "_merged.tif")))
  
  # merge start date cum diff stress
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "cum_diff_stress.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_cum_diff_stress_", i, "_merged.tif")))
  
  # merge start date dates stress
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "dates_stress.tif$", full.names = T)
  conf.res.die = conf.res.die[!grepl("nb_dates", conf.res.die)]
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_dates_stress_", i, "_merged.tif")))
  
  stress_durations = conf_merged[[2]] - conf_merged[[1]]# defined as the difference between first anomaly and first normal obs, second to second, ...
  
  for (m in 2:((nlyr(conf_merged)-1)/2)) stress_durations = c(stress_durations, conf_merged[[2*m]] - conf_merged[[2*m-1]])
  
  writeRaster(stress_durations, paste0(for_out_path, paste0("output_dates_stress_diff_", i, "_merged.tif")))
  
  gc()
  
  # merge nb date dates stress
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "nb_dates_stress.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_nb_dates_stress_", i, "_merged.tif")))
  
  # merge nb periods stress
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "nb_periods_stress.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_nb_periods_stress_", i, "_merged.tif")))
  
  # merge stress index
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "stress_index.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("output_stress_index_", i, "_merged.tif")))
  
  gc()
  
  # merge soil status
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "state_soil.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("state_soil_", i, "_merged.tif")))
  
  # merge soil count
  
  conf.res.die = list.files(dirs.out, recursive = T, pattern = "count_soil.tif$", full.names = T)
  
  conf_merged = vrt(conf.res.die)
  
  writeRaster(conf_merged, paste0(for_out_path, paste0("count_soil_", i, "_merged.tif")))
  
  gc()
}
